class_name Items
const script_name := "items"

const items := {

	sword_short_iron = {
		nickname = "Iron Short Sword",
		name = "sword",
		broadType = "weapons",
		type = "melee",
		subType = "one-handed sword",
		tags = [],
		description = "What time is it? Sword Time becuase Adventure Time is copyrighted",
		buffs = {
			strength = 2,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 0,
			agility = 0,
			luck = 0,
			melee = 10,
			mana = 0,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	},

	staff_small = {
		nickname = "Small Staff",
		name = "staff",
		broadType = "weapons",
		type = "magic",
		subType = "one-handed staff",
		tags = [],
		description = "Don't worry, no one thinks you need a walking stick *cough cough*",
		buffs = {
			strength = 0,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 2,
			agility = 0,
			luck = 0,
			melee = 0,
			mana = 10,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	},

	wand_wood = {
		nickname = "Wooden Wand",
		name = "wand",
		broadType = "weapons",
		type = "magic",
		subType = "wand",
		tags = [],
		description = "Looks like some random stick you would play with as a child",
		buffs = {
			strength = 0,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 2,
			agility = 0,
			luck = 0,
			melee = 0,
			mana = 10,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	},

	axe_battle = {
		nickname = "Battle Axe",
		name = "axe",
		broadType = "weapons",
		type = "melee",
		subType = "two-handed axe",
		tags = [],
		description = "It takes great strength to swing this into your targets",
		buffs = {
			strength = 3,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 0,
			agility = -1,
			luck = 0,
			melee = 20,
			mana = 0,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	},

	bow_hunting = {
		nickname = "Hunting bow",
		name = "bow",
		broadType = "weapons",
		type = "ranged",
		subType = "hunting bow",
		tags = [],
		description = "Perfect for hunting small animals... or children",
		buffs = {
			strength = 0,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 0,
			agility = 2,
			luck = 0,
			melee = 0,
			mana = 0,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	},

	arrow_wooden = {
		nickname = "Wooden Arrow",
		name = "arrow",
		broadType = "weapons",
		type = "consumables",
		subType = "arrow",
		tags = [],
		description = "Someone must have spent hours straightening and pointing sticks just so you could lose them when you miss",
		buffs = {
			strength = 0,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 0,
			agility = 0,
			luck = 1,
			melee = 4,
			mana = 0,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	},

	dagger_iron = {
		nickname = "Iron Dagger",
		name = "dagger",
		broadType = "weapons",
		type = "melee",
		subType = "dagger",
		tags = [],
		description = "Please, don't back stab your friends",
		buffs = {
			strength = 0,
			perception = 0,
			endurance = 0,
			charisma = 0,
			intelligence = 0,
			agility = 0,
			luck = 1,
			melee = 5,
			mana = 0,
			defense = 0
		},
		level = 1,
		levelRequirement = 1,
		quantity = 1,
	}
}
